### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by shubhodeep9** [shubhodeep9/torn#13]
Complete cli  module,
required tasks:

- [x] new: it is supposed to clone pytorn/app repo for creating a new app.
- [x] controller: create a new controller file 
- [x] version: print current torn version

**Comment by shubhodeep9** [comment]
https://github.com/pytorn/torn/blob/4499e7c903175da4a4d7dea39c190244552131c0/torn/plugins/console.py#L3
the logic for cli

**Comment by h93xV2** [comment]
I can work on this

**Comment by shubhodeep9** [comment]
@h93xV2 go ahead and create a PR

**Comment by h93xV2** [comment]
@shubhodeep9 I just started making the changes :laughing:. PR will be created in due time

**Comment by shubhodeep9** [comment]
New and version has been completed on #17

**Comment by Adi2612** [comment]
@shubhodeep9  
please provide more info about controller.
thanks

**Comment by shubhodeep9** [comment]
@Adi2612 
By new controller I mean
when a user types, `torn controller User` or `torn generate controller User`
it should create a file, that is the Controller by name UserController, with a default method for get request, 
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from torn.api import Controller

class UserController(Controller):
    def get(self):
        pass
```
So,
`torn generate controller Auth` should give
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from torn.api import Controller

class AuthController(Controller):
    def get(self):
        pass
```

**Comment by Adi2612** [comment]
> @Adi2612
> By new controller I mean
> when a user types, `torn controller User`
> it should create a file, that is the Controller by name UserController, with a default method for get request,
> 
> ```
> #!/usr/bin/env python
> # -*- coding: utf-8 -*-
> from torn.api import Controller
> 
> class UserController(Controller):
>     def get(self):
>         return "Hey"
> ```
So, whats the best way --> 
1.  writing line by line and making a separate file named "UserController" .
2. or add a file in main git repo. and downloading it whenever it is required.
I think the 2nd option is better because in that way updating  User Controller for future reference would be easier .
@shubhodeep9  what  U think ?

**Comment by shubhodeep9** [comment]
> > @Adi2612
> > By new controller I mean
> > when a user types, `torn controller User`
> > it should create a file, that is the Controller by name UserController, with a default method for get request,
> > ```
> > #!/usr/bin/env python
> > # -*- coding: utf-8 -*-
> > from torn.api import Controller
> > 
> > class UserController(Controller):
> >     def get(self):
> >         return "Hey"
> > ```
> 
> So, whats the best way -->
> 
> 1. writing line by line and making a separate file named "UserController" .
> 2. or add a file in main git repo. and downloading it whenever it is required.
>    I think the 2nd option is better because in that way updating  User Controller for future reference would be easier .
>    @shubhodeep9  what  U think ?

See the file needs to be variable, the user can give any name, according to that the name and content of the file needs to be set.
I guess, we can go with a templating method. Just to parse the string to the file.

**Comment by Adi2612** [comment]
okay will do in that way.

**Comment by Adi2612** [comment]
@shubhodeep9  
Can U please help in getting a dynamic string in argument , because when I took a dynamic argument for ex :- torn controller Adi , I'm getting an error telling Adi is not in choices. So help me with that how I can tweak my cli function and argparser for to get a string argument after controller argument only.
thanks

**Comment by shubhodeep9** [comment]
refer to arg_parse library, the nargs parameter is the one responsible for accepting arguments

**Comment by shubhodeep9** [comment]
@Adi2612 I pushed a hotfix for this. 
now the guidelines says
to create a new app, `torn new --name=<name_of_app>`
Hence you can use this `--name` param for your controller.
