### ISSUE TITLE
run() is passed an unexpected argument autoreload

### ISSUE THREAD

**Issue by ba11b0y** [shubhodeep9/torn#24]
The current example app passes `autoreload` as an argument to the `run` method while the implementation of `run` does not take any argument other than `routes`.
Instead add `autoreload` as a positional argument in the implementation of `run` [method](https://github.com/pytorn/torn/blob/943c120e5efc234460819a0b169a496835238d05/torn/api/app.py#L27) or change the example.

**Comment by ba11b0y** [comment]
@shubhodeep9 Can you please confirm on this.

**Comment by shubhodeep9** [comment]
Damn, didn't see that. @invinciblycool yes please do.
