### ISSUE TITLE
Add python3 compatibility.

### ISSUE THREAD

**Issue by ba11b0y** [shubhodeep9/torn#25]
Maybe this issue can stay here for a while till the whole framework is python3 compatible as we come across breaking code which needs to be ported.
Below are the issues I came across with, while running the test app with python3.

- [x] Replace `iteritems()` with `items()` in [app.py](https://github.com/pytorn/torn/blob/d0993fff1cc7eb76ca6585ca15121270a9bd0a4d/torn/plugins/app.py#L32)

**Comment by shubhodeep9** [comment]
I have made the lib python3 supported and removed support for python2
hence closing this issue
