### ISSUE TITLE
Reimagine routing

### ISSUE THREAD

**Issue by shubhodeep9** [shubhodeep9/torn#30]
While writing test for routing, I faced with some fundamental blockers.
We should rethink principles and syntax for torn's routing.

**Comment by shubhodeep9** [comment]
version 1:
```
route = Routing()

route.add('/', Controller)
route.add('/users/{userId}', Controller).args({ 'userId': '[0-9]+' })
```

and to handle methods, one needs to define corresponding methods in their controller
```
class Controller(torn.api.Controller):
    def get(self):
        self.return('hello world')
```

and if requested method is not defined, the app will throw `TornMethodNotAllowed`

**Comment by ba11b0y** [comment]
> While writing test for routing, I faced with some fundamental blockers.

I remember facing the same. Let's see if can come up with something new. Any new ideas? 🎊

**Comment by shubhodeep9** [comment]
I am trying to come up with an implementation for above mentioned version, will create draft in a while
@invinciblycool your inputs are appreciated
