### ISSUE TITLE
Logo for Torn

### ISSUE THREAD

**Issue by shubhodeep9** [shubhodeep9/torn#9]
Need for a logo for this application, that will be the logo for the organization too.

**Comment by ashwini0529** [comment]
@tstreamdoth can you help us with this?

**Comment by andeladenaro** [comment]
Hi.. My name is Andela Denaro, and I want to propose logo for your project. 
Here's my design. 
![torn](https://user-images.githubusercontent.com/35057858/45584980-fb307780-b906-11e8-8103-27419d6276b1.png)
I would appreciate hearing your opinion on this. Kind regards.

**Comment by shubhodeep9** [comment]
This is the reason why I love open source community.
@andeladenaro thanks a lot for your effort. I really do like the design.
@ashwini0529 what do you say?

**Comment by ashwini0529** [comment]
Hey, @andeladenaro thanks a lot for your effort! The logo looks awesome.
Maybe we can have Pytorn somewhere?

**Comment by shubhodeep9** [comment]
Hi @andeladenaro 
The logo looks awesome, it would be great if you could write "PyTorn" in place of "Torn".
Thanks in advance.

**Comment by andeladenaro** [comment]
Hi @ashwini0529 and @shubhodeep9, sorry for misunderstood your project name.. I will change the name in the logo. How about the colour? What do you prefer to use?

**Comment by ashwini0529** [comment]
I personally like the blue one and the green one! 🎉

**Comment by andeladenaro** [comment]
Here I've made the changes. What do you think?
![pytorn](https://user-images.githubusercontent.com/35057858/45586525-e530b000-b922-11e8-9484-77706809e4de.png)

**Comment by shubhodeep9** [comment]
Hey @andeladenaro its awesome. I'll create a repo for artwork, and why don't you create PR to the repo. Cool?

**Comment by andeladenaro** [comment]
Thats great! So, what colour did you choose? I will provide svg and png source in google drive too.

**Comment by shubhodeep9** [comment]
@andeladenaro, As @ashwini0529 said, the blue and green seem great.
And in PR provide the files as uploads.
And at every step you will be given full credits for the work.

**Comment by shubhodeep9** [comment]
@andeladenaro created a new repo https://github.com/pytorn/artwork
let's address it in https://github.com/pytorn/artwork/issues/1
Closing this issue.
